spring:
 application:
  name: config-server
 cloud:
  config:
   server:
    git:
     uri: https://github.com/latiaobo/hadesPro.git
     searchPaths: config
     #username: 
     #password: 
   label: master
server:
 port: 8801

